#import "conf.typ": ieee

#show: ieee.with(
  title: [Extracting Images and Displacements from Raw Spectral Domain Optical Coherence Tomography Data],
  abstract: [
    #lorem(40)
  ],
  index-terms: ("SD-OCT","SDPM", "Medical Imaging"),
  authors: (
    (
      name: "Jaeho Cho",
      department: [ECE444 - Bioinstrumentation and Sensing],
      organization: [The Cooper Union for the Advancement of Science and Art],
      location: [New York City, NY],
      email: "jaeho.cho@cooper.edu"
    ),
  ),
  bibliography: bibliography("refs.bib")
)

= Introduction
Optical coherence tomography (OCT) is an optical imaging modality that can perform high resolution, crosssectional imaging by measuring echoes of backscattered light. The unique features of OCT make it a powerful imaging modality for many fundamental research and clinical applications.

OCT performs internal imaging by measuring the magnitude and echo time delay of backscattered light. Cross-sectional images are generated by performing multiple axial measurements of echo time delay (Ascans) and scanning the incident optical beam transversely. This produces a two-dimensional data set, which represents the optical backscattering in a cross-sectional plane through the sample (Bscan).

Repeated Ascans at the same location as a function of time can be used to generate a time-resolved image (Mscan). This technique called Spectral domain phase microscopy (SDPM) is useful for measuring the displacement of structures within the sample.

Spectral domain optical coherence tomography (SD-OCT) is a type of OCT that uses a spectrometer to capture the interference pattern of light reflected from a sample and a reference arm. In SD-OCT, the source is broadband and continuous-wave, the reference arm length is fixed at a position approximately corresponding to the position of the sample, and the spectral interference pattern between the light returning from the reference arm and all depths in the sample is dispersed by a spectrometer and collected simultaneously on an array detector such as a photodiode array or charge-coupled device (CCD). The spectral information is then used to reconstruct depth-resolved images of the sample.

The detector current ($I_D$) can be expressed as a function of wavenumber ($k$), commonly known as the "spectral interferogram":
$
I_D (k) = rho/4 [S(k) (R_R + R_(S 1) + R_(S 2) + dots.h)]\

+ rho/2 [S(k) sum_(n = 1)^N sqrt(R_R R_(S_n)) cos (2k (z_R - z_(S_n)))]\

+ rho/4 [S(k) sum_(n != m = 1)^N sqrt(R_(S_n) R_(S_m)) cos (2k (z_(S_n) - z_(S_m)))]
$<eq:spectral-interferogram>
where $rho$ is the responsivity of the detector, $S(k)$ is the spectral dependence of the light source, $R_R$ is the power reflectivity of the reference reflector, $R_{S_n}$ is the power reflectivity of the sample reflector, and $z_R$ and $z_{S_n}$ are the pathlength variables in the reference and sample arms measured from the beamsplitters, respectively. The first component is the "DC Terms", the second is the "Cross-correlation Terms" and the third is the "Auto-correlation Terms" @izattTheoryOpticalCoherence2008.

The internal reflectivity profile of the sample can be estimated from the inverse Fourier transform of $I_D (k)$, generating an Ascan expressed as:

#box(
  text(size: 9pt)[
    $
    i_D (z) = rho / 8 [gamma (z) [R_R + R_(S 1) + R_(S 2) + dots.h]]\
    + rho / 4 sum_(n = 1)^N sqrt(R_R R_(S_n)) [gamma [2 (z_R - z_(S_n))] + gamma [-2 (z_R - z_(S_n))] ]\
    + rho / 8 sum_(n != m = 1)^N sqrt(R_(S_n) R_(S_m)) [gamma [2 (z_(S_n) - z_(S_m))] + gamma [-2 (z_(S_n) - z_(S_m))]]
    $
    ]
)
where $gamma(z)$ is inverse Fourier transform of the source spectrum @izattTheoryOpticalCoherence2008.

= Methodology
== Data Acquisition
The raw data were acquired in air, which has of an index of refraction ($n$) of $1$, using a ThorLabs Telesto 3, which uses an SLD with a center wavelength ($lambda_0$) of $1310 "nm"$, bandwidth ($Delta lambda$) of $100 "nm"$; and an LSM-03 objective lens with numerical aperture ($"NA"$) of $0.055$. Raw OCT data were collected in the form of Ascans, with each Ascan containing 2048 pixels each representing a depth of $3.6 thick mu"m"$.

Assuming that the lateral resolution is limited by the confocal geometrical optics, and the axial resolution is limited by the low-coherence interferometer; the lateral resolution ($delta x$) can be calculated as,
$
delta x = 0.37 lambda_0 / "NA" approx 8.81 thick mu"m"
$
and the axial resolution ($delta z$),
$
delta z = l_c = (2 ln(2)) / pi lambda_0^2 / (Delta lambda) approx 7.57 thick mu"m"
$
where $l_c$ is the coherence length @izattTheoryOpticalCoherence2008.

To improve the signal-to-noise ratio (SNR) and reduce artifacts, background scans were collected along with the sample scans to perform background subtraction. 

As the sample was kept entirely to one side of the zero path length, the mirror image artifacts can be simply removed by displaying only the positive distances @izattTheoryOpticalCoherence2008. This correction results in the pixel aspect ratio of the Bscans to be double that of images without accounting for the mirror image artifacts; approximately $0.271$ instead of $0.136$. 

== Image Processing
All processing and analysis were performed using MATLAB. 

=== Ascan
The raw data is initially captured as interferometric measurements given by the detector current. To reconstruct the internal sample reflectivity profile, the detector current first needs to be transformed from their original wavelength-based form into a uniformly spaced wavenumber (k-space) domain, which can be accomplished by a matrix multiplication. As can be seen in @fig:ascan-processing, the transformation to the k-domain does not significantly change the actual signal.
Next, the signal undergoes background subtraction, where the average of the background scans is subtracted from the sample scan. This step is effective for removing the DC component in equation @eq:spectral-interferogram. 

Next, any consistent background signals, which may include fixed noise patterns or unwanted stationary reflections, are removed by averaging several reference scans and subtracting this average from each measurement. The resulting signals are then smoothed and filtered using a windowing function to minimize spectral leakage and reduce artifacts. Optionally, deconvolution is performed to compensate for system-induced distortions, further enhancing resolution and image quality. Finally, these processed signals undergo a Fourier transform to translate them from the frequency domain into spatial coordinates, producing the depth-resolved reflectivity profiles that collectively form the final Bscan image.

#figure(
  image("figures/Ascan_Processing.png"),
  caption: [Generation of an Ascan from Detector Current to reflectivity. The raw data is transformed from wavelength to wavenumber, followed by background subtraction, windowing, and deconvolution. The final step involves a Fourier transform to obtain the depth-resolved reflectivity profile.]
)<fig:ascan-processing>
#colbreak()

#figure(
  image("figures/Detector_Current.png"),
  caption: [Comparison of raw detector currents from the sample and background scans. ]
)

// #place(
//   auto,
//   scope: "column",
//   float: true,
//   [#figure(
//     caption: [Fano Factor],
//     table(
//       columns: 4,
//       stroke: (x, y) => if y <= 1 { (top: 0.5pt) },
//       fill: (x, y) => if y > 0 and calc.rem(y, 2) == 0  { rgb("#efefef") },

//       table.header[Process][$sigma^2_n$][$angle.l n angle.r$][Fano Factor],
//       [Homogeneous],[59.77],[59.82],[1.00],
//       [Homogeneous w/ Refractory Effects],[17.20],[36.26],[0.47],
//       [Inhomogeneous],[24.47],[24.45],[1.00],
//       [Inhomogeneous w/ Refractory Effects],[9.66],[16.73],[0.57],
//     )
//   )<tab:fano-factor>]
// )
// 
=== Bscan
The Bscan data consisted of $10,000$ Ascans of the sample, and $175$ backgrounds. 

=== Mscan

= Results

// #figure(
//   image("figures/.png"),
//   caption: []
// )<fig:>
// figures/Ascan_Analysis_Bscan.png figures/Ascan_Magnitude_Mscan1.png figures/Ascan_Magnitude_Mscan40.png figures/Ascan_Processing.png figures/Ascan_Processing_Comparison.png figures/Ascans.png figures/Bscan_Processing.png figures/Bscan_Focused.png figures/Bscans.png figures/Detector_Current.png figures/Displacement_Freq_Mscan1_Peak1.png figures/Displacement_Freq_Mscan1_Peak2.png figures/Displacement_Freq_Mscan40_Peak1.png figures/Displacement_Freq_Mscan40_Peak2.png figures/Displacement_Time_Mscan1_Peak1.png figures/Displacement_Time_Mscan1_Peak2.png figures/Displacement_Time_Mscan40_Peak1.png figures/Displacement_Time_Mscan40_Peak2.png
#figure(
  image("figures/Ascans.png"),
  caption: [Ascans of the raw data. A) the first Ascan of the Bscan data B) Ascan at the center of the Bscan data C) Ascan at the center of the Mscan1 data D) Ascan at the center of the Mscan40 data]
)<fig:ascan>

#figure(
  image("figures/Bscans.png"),
  caption: [Bscans of the raw data. A) the first Bscan of the Bscan data B) Bscan at the center of the Mscan1 data C) Bscan at the center of the Mscan40 data]
)<fig:bscan>


= Discussion

// TODO: time markers of processing

=== Image Reconstruction Improvements
Processed images significantly reduced background noise and mirror artifacts. Contrast enhancement using polynomial background fitting provided clear differentiation between layers, allowing precise identification of physical structures, such as tape layers.

=== Displacement Measurement Accuracy
The accuracy of sub-pixel displacement measurements was confirmed through spectral domain phase microscopy. Frequency domain analysis verified expected speaker output frequencies, supporting the system’s sensitivity in measuring subtle displacements.

=== Methodological Considerations
The processing pipeline’s efficiency was evaluated by timing computational steps. Background subtraction and deconvolution notably improved signal clarity, despite adding computational overhead. Future implementations could optimize processing time further by employing parallel processing techniques or GPU acceleration.

=== Future Work
Coupled with catheter, endoscopic, laparoscopic, or needle delivery devices, OCT promises to have a powerful impact on many medical applications ranging from the diagnosis of neoplasia, to enabling new minimally invasive surgical procedures.